language: java
dist: xenial
sudo: false

branches:
  except:
    - gh-pages

env:
  global:
  - secure: SSdy5NKn2n5zB3ZybM7Ma3R8Yq2DtlemsJmJrgiERdfaVJfsjbpbS/8jsf2bKf60B4QlPbFbS/wtlTCkzmQzDyN9eQ9NCtlulb2wCMav4ChYJLZAKmGuciGStemA+kIhDYvxvVYLsPANCaDWDt4UPpnDIpVkp4EFxI2GuNoWlKXhcpUqq4Eu51JeyNsfXjoJl2kyvKguRK8hacWvp1ecqJ/lEa3xhKy98UCMfZuGfMyeT2VAV7jE3RLHR93UWDECUzGsqxhmzXaBwpO5Ejn2V6m1MX1FaAdkRPL2oPPimR1yT05vUjzwSdJ/SLCVwIBCvhUqIAa4dKUbLSEZ1ABlGW9vTCnqFsvleAKL/4nVurjvapZuKAk1MIa3iMTOByQjcvDIuiI8f3+MlsZv7nNA3za/r7eOCOAFrnXNjoqeokBmHxCCJnX8sfSLxUykaNSOScylTVIWlt7ILGFZgalo4LEWce1eS3sNVu1lSQI9WJZh1oZ79Ad1Y64t7rEYVNfs2Mr3RomAP8DsSgCfTKnqPrrVzUJAeI6foULN+yxAyJS6G/b3JpmN0pg+J5dmIf5jEjQTT2YCn7NSygRRu6EhlBJwpRA/UrAOfQmtK/RmByJMtuZJu+f+YAmNW7VorlG+1/dGSNMOvf4A91dipek1gJ6nknadj8HXxbjb3GQg3xQ=

addons:
  apt:
    update: true

matrix:
  include:
    - name: "Java 8 Tests"
      jdk: oraclejdk8
      script: travis_retry mvn test
    - name: "Coverage"
      jdk: oraclejdk8
      env: TESTENV=cover FYI="this also builds documentation for tags"
      script: mvn clean cobertura:cobertura
      addons:
        apt:
          packages:
            - python3
            - python3-pip
            - python-virtualenv
            - make

after_success:
  - '[[ "$TESTENV" == "cover" ]] && bash <(curl -s https://codecov.io/bash)'
  - '[[ "$TESTENV" == "cover" ]] && [[ -n "$TRAVIS_TAG" ]] && ./deploy-docs.sh'
